---
# tasks file for roles/os_hardening

- name: Harden /etc/login.defs - Set PASS_MAX_DAYS
  ansible.builtin.lineinfile:
    path: /etc/login.defs
    regexp: '^PASS_MAX_DAYS\s+\d+' # Tìm dòng bắt đầu bằng PASS_MAX_DAYS theo sau là số
    line: 'PASS_MAX_DAYS   90' # Dòng thay thế
    state: present
    backrefs: yes # Sử dụng regexp để tìm dòng thay thế, nếu không tìm thấy thì không làm gì
    # Hoặc dùng insertafter nếu muốn đảm bảo dòng được thêm vào nếu không có:
    # insertafter: '^#\s+PASS_MAX_DAYS' # Chèn sau dòng comment mặc định (nếu có)
    # state: present
  become: true

- name: Harden /etc/security/pwquality.conf - Set password policies
  ansible.builtin.lineinfile:
    path: /etc/security/pwquality.conf
    regexp: "^{{ item.key }}( =.*)?$" # Tìm dòng bắt đầu bằng key, có thể có dấu = hoặc không
    line: "{{ item.key }} = {{ item.value }}" # Dòng đảm bảo tồn tại
    state: present
    create: true # Tạo file nếu chưa có (mặc dù file này thường có sẵn)
    owner: root
    group: root
    mode: '0644'
  become: true
  loop:
  - { key: 'minlen', value: '8' }
  - { key: 'minclass', value: '4' }
  - { key: 'lcredit', value: '-1' }
  - { key: 'ucredit', value: '-1' }
  - { key: 'dcredit', value: '-1' }
  - { key: 'ocredit', value: '-1' }

- name: Harden /etc/security/faillock.conf - Set failure lock policies
  ansible.builtin.lineinfile:
    path: /etc/security/faillock.conf
    regexp: "^{{ item.key }}( =.*)?$"
    line: "{{ item.key }} = {{ item.value }}"
    state: present
    create: true
    owner: root
    group: root
    mode: '0644'
  become: true
  loop:
  - { key: 'deny', value: '5' }
  - { key: 'unlock_time', value: '300' }

- name: Configure session timeout script /etc/profile.d/tct_sessiontimeout.sh
  ansible.builtin.copy:
    dest: /etc/profile.d/tct_sessiontimeout.sh
    content: |
      #!/bin/sh
      # Set session timeout - Managed by Ansible
      readonly TMOUT=300
      export TMOUT
    owner: root
    group: root
    mode: '0755' # Cần quyền thực thi cho các script trong profile.d
  become: true
